# Generated by Django 2.2 on 2020-02-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20200207_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_trashed',
            new_name='is_bin',
        ),
    ]
