# Generated by Django 2.2 on 2020-02-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200206_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
