# Generated by Django 2.2 on 2020-02-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20200207_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='link',
            new_name='more',
        ),
    ]
