# Generated by Django 2.2 on 2020-02-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_auto_20200207_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='image',
            new_name='add_image',
        ),
    ]
